Compilation fixed for kernel 5.10.x
openucx/xpmem pull request #6
Opened 2020-12-28 01:25 UTC by alex--m

Signed-off-by: Alex Margolin <alex.margolin@huawei.com>

2020-12-28 18:21 UTC, shamisp requested changes

2020-12-28 18:21 UTC, shamisp commented on kernel/xpmem_mmu_notifier.c
> -#include <asm/tlb.h>
@alex--m you have to ifdef this include for versions below 5.10.x. For an example grep for LINUX_VERSION_CODE in the code

2021-01-15 02:03 UTC, shamisp commented
@alex--m I'm running 5.10.6-200.fc33.aarch64 and I don't see this compilation issue.

2021-06-29 17:04 UTC, yosefe commented
related to https://github.com/hjelmn/xpmem/pull/48

2021-06-29 17:20 UTC, shamisp commented
@yosefe I don't have any x86 to test. If you confirm it works, I will merge,

2021-06-29 17:21 UTC, shamisp commented
@yosefe also, probably should be wrapped with LINUX_VERSION_CODE

2021-06-30 06:38 UTC, tzafrir-mellanox commented
I tested building with kernel 5.0 and older stable branches. 4.9 and below fail to build anyway. 4.14 and above work fine with the fix.

2021-06-30 06:39 UTC, tzafrir-mellanox commented
Also, as I noted in #43, for me the build fails starting from kernel 5.8.

2021-06-30 16:40 UTC, merged